function popup() {
  let xys = [];
  for (let i = 0; i < document.querySelectorAll(".inpy").length; i++) {
    xys.push([
      +document.querySelectorAll(".inpx")[i].value,
      +document.querySelectorAll(".inpy")[i].value,
    ]);
  }

  // Costruzione della stringa con i valori dell'array
  const dataString = xys.map((pair) => `{${pair.join(",")}}`).join(",");

  // Costruzione dell'URL con la stringa dei dati
  const urlString = `https://www.wolframalpha.com/input?i=polynomial+regression&assumption=%7B%22C%22%2C+%22polynomial+regression%22%7D+-%3E+%7B%22Calculator%22%2C+%22dflt%22%7D&assumption=%7B%22F%22%2C+%22InterpolatingPolynomialCalculator%22%2C+%22data2%22%7D+-%3E%22%7B${dataString}%7D%22`;

  localStorage.setItem("url", urlString);
  setTimeout(function(){
    localStorage.removeItem('url')
  },1000)
}
function refocus() {
  document.querySelectorAll("input").forEach((e) => {
    e.addEventListener("keypress", (p) => {
      if (p.key == "Enter") {
        let vai = false,
          fatto = false;

        document.querySelectorAll("input").forEach((el) => {
          if (vai && !fatto) {
            el.focus();
            fatto = true;
          }
          if (el == e) {
            vai = true;
          }
        });
      }
    });
  });
  document
    .querySelectorAll("input")
    [document.querySelectorAll("input").length - 1].addEventListener(
      "keypress",
      (e) => {
        if (e.key == "Enter") {
          document.querySelector("#piu").click();
        }
      }
    );
  document
    .querySelectorAll("input")
    [document.querySelectorAll("input").length - 2].focus();
}
document.addEventListener("DOMContentLoaded", function () {
  document.getElementById("invia").addEventListener("click", function(){
    document.querySelector('#c').innerHTML+=`<svg id="mC1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <path fill="none" stroke="#e90c59" stroke-width="8" stroke-dasharray="42.76482137044271 42.76482137044271" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round" style="transform:scale(0.8);transform-origin:50px 50px">
      <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0;256.58892822265625"></animate>
    </path>
    <!-- [ldio] generated by https://loading.io/ --></svg>`
    popup();
  });
  document.querySelector("#piu").addEventListener("click", function () {
    let a = document.createElement("div");
    a.classList.add("xy");
    a.innerHTML =`
      
    <div class="x">
          
    <div class="text">x: </div>
    <input class="inpx">
    </div>
    <div class="y">
      
    <div class="text">y: </div>
    <input class="inpy">
    </div>
  `
    document.querySelector("#mygrid").appendChild(a);

    refocus();
  });
  refocus();
});